export const countryData = [
    { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", flag:'AE' },
    { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", flag: 'AF' },
    { code: "ALL", name: "Albanian Lek", country: "Albania" },
    { code: "AMD", name: "Armenian Dram", country: "Armenia" },
    { code: "ANG", name: "Netherlands Antillian Guilder", country: "Netherlands Antilles" },
    { code: "AOA", name: "Angolan Kwanza", country: "Angola" },
    { code: "ARS", name: "Argentine Peso", country: "Argentina" },
    { code: "AUD", name: "Australian Dollar", country: "Australia" },
    { code: "AWG", name: "Aruban Florin", country: "Aruba" },
    { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan" },
    { code: "BAM", name: "Bosnia and Herzegovina Mark", country: "Bosnia and Herzegovina" },
    { code: "BBD", name: "Barbados Dollar", country: "Barbados" },
    { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh" },
    { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria" },
    { code: "BHD", name: "Bahraini Dinar", country: "Bahrain" },
    { code: "BIF", name: "Burundian Franc", country: "Burundi" },
    { code: "BMD", name: "Bermudian Dollar", country: "Bermuda" },
    { code: "BND", name: "Brunei Dollar", country: "Brunei" },
    { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia" },
    { code: "BRL", name: "Brazilian Real", country: "Brazil" },
    { code: "BSD", name: "Bahamian Dollar", country: "Bahamas" },
    { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan" },
    { code: "BWP", name: "Botswana Pula", country: "Botswana" },
    { code: "BYN", name: "Belarusian Ruble", country: "Belarus" },
    { code: "BZD", name: "Belize Dollar", country: "Belize" },
    { code: "CAD", name: "Canadian Dollar", country: "Canada" },
    { code: "CDF", name: "Congolese Franc", country: "Democratic Republic of the Congo" },
    { code: "CHF", name: "Swiss Franc", country: "Switzerland" },
    { code: "CLP", name: "Chilean Peso", country: "Chile" },
    { code: "CNY", name: "Chinese Yuan", country: "China" },
    { code: "COP", name: "Colombian Peso", country: "Colombia" },
    { code: "CRC", name: "Costa Rican Colon", country: "Costa Rica" },
    { code: "HRK", name: "Croatian Kuna", country: "Croatia" },
    { code: "CUP", name: "Cuban Peso", country: "Cuba" },
    { code: "CZK", name: "Czech Koruna", country: "Czech Republic" },
    { code: "DKK", name: "Danish Krone", country: "Denmark" },
    { code: "DJF", name: "Djiboutian Franc", country: "Djibouti" },
    { code: "DOP", name: "Dominican Peso", country: "Dominican Republic" },
    { code: "EGP", name: "Egyptian Pound", country: "Egypt" },
    { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea" },
    { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia" },
    { code: "EUR", name: "Euro", country: "Andorra, Austria, Belgium, Cyprus, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Kosovo, Luxembourg, Malta, Montenegro, Netherlands, Portugal, San Marino, Slovenia, Slovakia, Spain" },
    { code: "FJD", name: "Fijian Dollar", country: "Fiji" },
    { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands" },
    { code: "GBP", name: "British Pound Sterling", country: "United Kingdom, South Georgia and the South Sandwich Islands, British Antarctic Territory, Tristan da Cunha" },
    { code: "GEL", name: "Georgian Lari", country: "Georgia" },
    { code: "GGP", name: "Guernsey Pound", country: "Guernsey" },
    { code: "GHS", name: "Ghanaian Cedi", country: "Ghana" },
    { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar" },
    { code: "GMD", name: "Gambian Dalasi", country: "Gambia" },
    { code: "GNF", name: "Guinean Franc", country: "Guinea" },
    { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala" },
    { code: "GYD", name: "Guyanaese Dollar", country: "Guyana" },
    { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong" },
    { code: "HNL", name: "Honduran Lempira", country: "Honduras" },
    { code: "HRK", name: "Croatian Kuna", country: "Croatia" },
    { code: "HTG", name: "Haitian Gourde", country: "Haiti" },
    { code: "HUF", name: "Hungarian Forint", country: "Hungary" },
    { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia" },
    { code: "ILS", name: "Israeli New Shekel", country: "Israel" },
    { code: "INR", name: "Indian Rupee", country: "India" },
    { code: "IQD", name: "Iraqi Dinar", country: "Iraq" },
    { code: "IRR", name: "Iranian Rial", country: "Iran" },
    { code: "ISK", name: "Icelandic Króna", country: "Iceland" },
    { code: "JMD", name: "Jamaican Dollar", country: "Jamaica" },
    { code: "JOD", name: "Jordanian Dinar", country: "Jordan" },
    { code: "JPY", name: "Japanese Yen", country: "Japan" },
    { code: "KES", name: "Kenyan Shilling", country: "Kenya" },
    { code: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan" },
    { code: "KHR", name: "Cambodian Riel", country: "Cambodia" },
    { code: "KMF", name: "Comorian Franc", country: "Comoros" },
    { code: "KPW", name: "North Korean Won", country: "North Korea" },
    { code: "KRW", name: "South Korean Won", country: "South Korea" },
    { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait" },
    { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands" },
    { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan" },
    { code: "LAK", name: "Lao Kip", country: "Laos" },
    { code: "LBP", name: "Lebanese Pound", country: "Lebanon" },
    { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka" },
    { code: "LRD", name: "Liberian Dollar", country: "Liberia" },
    { code: "LSL", name: "Lesotho Loti", country: "Lesotho" },
    { code: "LTL", name: "Lithuanian Litas", country: "Lithuania" },
    { code: "LVL", name: "Latvian Lats", country: "Latvia" },
    { code: "LYD", name: "Libyan Dinar", country: "Libya" },
    { code: "MAD", name: "Moroccan Dirham", country: "Morocco" },
    { code: "MDL", name: "Moldovan Leu", country: "Moldova" },
    { code: "MGA", name: "Malagasy Ariary", country: "Madagascar" },
    { code: "MKD", name: "Macedonian Denar", country: "North Macedonia" },
    { code: "MMK", name: "Myanma Kyat", country: "Myanmar (Burma)" },
    { code: "NOK", name: "Norwegian Krone", country: "Norway" },
    { code: "NPR", name: "Nepalese Rupee", country: "Nepal" },
    { code: "NZD", name: "New Zealand Dollar", country: "New Zealand" },
    { code: "OMR", name: "Omani Rial", country: "Oman" },
    { code: "PEN", name: "Peruvian Sol", country: "Peru" },
    { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea" },
    { code: "PHP", name: "Philippine Peso", country: "Philippines" },
    { code: "PKR", name: "Pakistani Rupee", country: "Pakistan" },
    { code: "PLN", name: "Polish Zloty", country: "Poland" },
    { code: "PYG", name: "Paraguayan Guarani", country: "Paraguay" },
    { code: "QAR", name: "Qatari Riyal", country: "Qatar" },
    { code: "RON", name: "Romanian Leu", country: "Romania" },
    { code: "RSD", name: "Serbian Dinar", country: "Serbia" },
    { code: "RUB", name: "Russian Ruble", country: "Russia" },
    { code: "RWF", name: "Rwandan Franc", country: "Rwanda" },
    { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia" },
    { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands" },
    { code: "SCR", name: "Seychellois Rupee", country: "Seychelles" },
    { code: "SDG", name: "Sudanese Pound", country: "Sudan" },
    { code: "SEK", name: "Swedish Krona", country: "Sweden" },
    { code: "SGD", name: "Singapore Dollar", country: "Singapore" },
    { code: "SHP", name: "Saint Helenian Pound", country: "Saint Helena" },
    { code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone" },
    { code: "SOS", name: "Somali Shilling", country: "Somalia" },
    { code: "SRD", name: "Surinamese Dollar", country: "Suriname" },
    { code: "SSP", name: "South Sudanese Pound", country: "South Sudan" },
    { code: "STD", name: "São Tomé and Principe Dobra", country: "São Tomé and Principe" },
    { code: "SVC", name: "Salvadoran Colón", country: "El Salvador" },
    { code: "SYP", name: "Syrian Pound", country: "Syria" },
    { code: "SZL", name: "Swazi Lilangeni", country: "Swaziland" },
    { code: "THB", name: "Thai Baht", country: "Thailand" },
    { code: "TRY", name: "Turkish Lira", country: "Turkey" },
    { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan" },
    { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine" },
    { code: "USD", name: "United States Dollar", country: "United States of America" },
    { code: "VND", name: "Vietnamese Dong", country: "Vietnam" },
    { code: "XOF", name: "West African CFA franc", country: "West African Economic and Monetary Union (UEMOA)" },
    { code: "ZAR", name: "South African Rand", country: "South Africa" },
    ]
