export const countryData = [
    { code: "AED", name: "UAE Dirham", country: "United Arab Emirates", flag:'AE'},
    { code: "AFN", name: "Afghan Afghani", country: "Afghanistan", flag: 'AF'},
    { code: "ALL", name: "Albanian Lek", country: "Albania", flag: 'AL'},
    { code: "AMD", name: "Armenian Dram", country: "Armenia", flag:'AM'},
    { code: "ANG", name: "Netherlands Antillian Guilder", country: "Netherlands Antilles", flag: 'NL'},
    { code: "AOA", name: "Angolan Kwanza", country: "Angola", flag: 'AO'},
    { code: "ARS", name: "Argentine Peso", country: "Argentina", flag: 'AR'},
    { code: "AUD", name: "Australian Dollar", country: "Australia", flag: 'AU'},
    { code: "AWG", name: "Aruban Florin", country: "Aruba", flag: 'AW'},
    { code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", flag: 'AZ'},
    { code: "BAM", name: "Bosnia and Herzegovina Mark", country: "Bosnia and Herzegovina", flag: 'BA'},
    { code: "BBD", name: "Barbados Dollar", country: "Barbados", flag: 'BB'},
    { code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", flag: 'BD'},
    { code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", flag: 'BG'},
    { code: "BHD", name: "Bahraini Dinar", country: "Bahrain", flag: 'BH'},
    { code: "BIF", name: "Burundian Franc", country: "Burundi", flag: 'BI'},
    { code: "BMD", name: "Bermudian Dollar", country: "Bermuda", flag: 'BM'},
    { code: "BND", name: "Brunei Dollar", country: "Brunei", flag: 'BN'},
    { code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", flag: 'BO'},
    { code: "BRL", name: "Brazilian Real", country: "Brazil", flag: 'BR'},
    { code: "BSD", name: "Bahamian Dollar", country: "Bahamas", flag: 'BS'},
    { code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", flag: 'BT'},
    { code: "BWP", name: "Botswana Pula", country: "Botswana", flag: 'BW'},
    { code: "BYN", name: "Belarusian Ruble", country: "Belarus", flag: 'BY'},
    { code: "BZD", name: "Belize Dollar", country: "Belize", flag: 'BZ'},
    { code: "CAD", name: "Canadian Dollar", country: "Canada", flag: 'CA'},
    { code: "CDF", name: "Congolese Franc", country: "Democratic Republic of the Congo", flag: 'CD'},
    { code: "CHF", name: "Swiss Franc", country: "Switzerland", flag: 'CH'},
    { code: "CLP", name: "Chilean Peso", country: "Chile", flag: 'CL'},
    { code: "CNY", name: "Chinese Yuan", country: "China", flag: 'CN'},
    { code: "COP", name: "Colombian Peso", country: "Colombia", flag: 'CO'},
    { code: "CRC", name: "Costa Rican Colon", country: "Costa Rica", flag: 'CR'},
    { code: "HRK", name: "Croatian Kuna", country: "Croatia", flag: 'HR'},
    { code: "CUP", name: "Cuban Peso", country: "Cuba", flag: 'CU'},
    { code: "CZK", name: "Czech Koruna", country: "Czech Republic", flag: 'CZ'},
    { code: "DKK", name: "Danish Krone", country: "Denmark", flag: 'DK'},
    { code: "DJF", name: "Djiboutian Franc", country: "Djibouti", flag: 'DJ'},
    { code: "DOP", name: "Dominican Peso", country: "Dominican Republic", flag: 'DO'},
    { code: "EGP", name: "Egyptian Pound", country: "Egypt", flag: 'EG'},
    { code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", flag: 'ER'},
    { code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", flag: 'ET'},
    { code: "EUR", name: "Euro", country: "Andorra, Austria, Belgium, Cyprus, Estonia, Finland, France, Germany, Greece, Ireland, Italy, Kosovo, Luxembourg, Malta, Montenegro, Netherlands, Portugal, San Marino, Slovenia, Slovakia, Spain", flag: 'EU'},
    { code: "FJD", name: "Fijian Dollar", country: "Fiji", flag: 'FJ'},
    { code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands", flag: 'FK'},
    { code: "GBP", name: "British Pound Sterling", country: "United Kingdom, South Georgia and the South Sandwich Islands, British Antarctic Territory, Tristan da Cunha", flag: 'GB'},
    { code: "GEL", name: "Georgian Lari", country: "Georgia", flag: 'GE'},
    { code: "GGP", name: "Guernsey Pound", country: "Guernsey", flag: 'GG'},
    { code: "GHS", name: "Ghanaian Cedi", country: "Ghana", flag: 'GH'},
    { code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", flag: 'GI'},
    { code: "GMD", name: "Gambian Dalasi", country: "Gambia", flag: 'GM'},
    { code: "GNF", name: "Guinean Franc", country: "Guinea", flag: 'GN'},
    { code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", flag: 'GT'},
    { code: "GYD", name: "Guyanaese Dollar", country: "Guyana", flag: 'GY'},
    { code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", flag: 'HK'},
    { code: "HNL", name: "Honduran Lempira", country: "Honduras", flag: 'HN'},
    { code: "HRK", name: "Croatian Kuna", country: "Croatia", flag: 'HR'},
    { code: "HTG", name: "Haitian Gourde", country: "Haiti", flag: 'HT'},
    { code: "HUF", name: "Hungarian Forint", country: "Hungary", flag: 'HU'},
    { code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", flag: 'ID'},
    { code: "ILS", name: "Israeli New Shekel", country: "Israel", flag: 'IL'},
    { code: "INR", name: "Indian Rupee", country: "India", flag: 'IN'},
    { code: "IQD", name: "Iraqi Dinar", country: "Iraq", flag: 'IQ'},
    { code: "IRR", name: "Iranian Rial", country: "Iran", flag: 'IR'},
    { code: "ISK", name: "Icelandic Króna", country: "Iceland", flag: 'IS'},
    { code: "JMD", name: "Jamaican Dollar", country: "Jamaica", flag: 'JM'},
    { code: "JOD", name: "Jordanian Dinar", country: "Jordan", flag: 'JO'},
    { code: "JPY", name: "Japanese Yen", country: "Japan", flag: 'JP'},
    { code: "KES", name: "Kenyan Shilling", country: "Kenya", flag: 'KE'},
    { code: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan", flag: 'KG'},
    { code: "KHR", name: "Cambodian Riel", country: "Cambodia", flag: 'KH'},
    { code: "KMF", name: "Comorian Franc", country: "Comoros", flag: 'KM'},
    { code: "KPW", name: "North Korean Won", country: "North Korea", flag: 'KP'},
    { code: "KRW", name: "South Korean Won", country: "South Korea", flag: 'KR'},
    { code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", flag: 'KW'},
    { code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", flag: 'KY'},
    { code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", flag: 'KZ'},
    { code: "LAK", name: "Lao Kip", country: "Laos", flag: 'LA'},
    { code: "LBP", name: "Lebanese Pound", country: "Lebanon", flag: 'LB'},
    { code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", flag: 'LK'},
    { code: "LRD", name: "Liberian Dollar", country: "Liberia", flag: 'LR'},
    { code: "LSL", name: "Lesotho Loti", country: "Lesotho", flag: 'LS'},
    { code: "LTL", name: "Lithuanian Litas", country: "Lithuania", flag: 'LT'},
    { code: "LVL", name: "Latvian Lats", country: "Latvia", flag: 'LV'},
    { code: "LYD", name: "Libyan Dinar", country: "Libya", flag: 'LY'},
    { code: "MAD", name: "Moroccan Dirham", country: "Morocco", flag: 'MA'},
    { code: "MDL", name: "Moldovan Leu", country: "Moldova", flag: 'MD'},
    { code: "MGA", name: "Malagasy Ariary", country: "Madagascar", flag: 'MG'},
    { code: "MKD", name: "Macedonian Denar", country: "North Macedonia", flag: 'MK'},
    { code: "MMK", name: "Myanma Kyat", country: "Myanmar (Burma)", flag: 'MM'},
    { code: "NOK", name: "Norwegian Krone", country: "Norway", flag: 'NO'},
    { code: "NPR", name: "Nepalese Rupee", country: "Nepal", flag: 'NP'},
    { code: "NZD", name: "New Zealand Dollar", country: "New Zealand", flag: 'NZ'},
    { code: "OMR", name: "Omani Rial", country: "Oman", flag: 'OM'},
    { code: "PEN", name: "Peruvian Sol", country: "Peru", flag: 'PE'},
    { code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", flag: 'PG'},
    { code: "PHP", name: "Philippine Peso", country: "Philippines", flag: 'PH'},
    { code: "PKR", name: "Pakistani Rupee", country: "Pakistan", flag: 'PK'},
    { code: "PLN", name: "Polish Zloty", country: "Poland", flag: 'PL'},
    { code: "PYG", name: "Paraguayan Guarani", country: "Paraguay", flag: 'PY'},
    { code: "QAR", name: "Qatari Riyal", country: "Qatar", flag: 'QA'},
    { code: "RON", name: "Romanian Leu", country: "Romania", flag: 'RO'},
    { code: "RSD", name: "Serbian Dinar", country: "Serbia", flag: 'RS'},
    { code: "RUB", name: "Russian Ruble", country: "Russia", flag: 'RU'},
    { code: "RWF", name: "Rwandan Franc", country: "Rwanda", flag: 'RW'},
    { code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", flag: 'SA'},
    { code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", flag: 'SB'},
    { code: "SCR", name: "Seychellois Rupee", country: "Seychelles", flag: 'SC'},
    { code: "SDG", name: "Sudanese Pound", country: "Sudan", flag: 'SD'},
    { code: "SEK", name: "Swedish Krona", country: "Sweden", flag: 'SE'},
    { code: "SGD", name: "Singapore Dollar", country: "Singapore", flag: 'SG'},
    { code: "SHP", name: "Saint Helenian Pound", country: "Saint Helena", flag: 'SH'},
    { code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone", flag: 'SL'},
    { code: "SOS", name: "Somali Shilling", country: "Somalia", flag: 'SO'},
    { code: "SRD", name: "Surinamese Dollar", country: "Suriname", flag: 'SR'},
    { code: "SSP", name: "South Sudanese Pound", country: "South Sudan", flag: 'a'},
    { code: "STD", name: "São Tomé and Principe Dobra", country: "São Tomé and Principe", flag: 'ST'},
    { code: "SVC", name: "Salvadoran Colón", country: "El Salvador", flag: 'SV'},
    { code: "SYP", name: "Syrian Pound", country: "Syria", flag: 'SY'},
    { code: "SZL", name: "Swazi Lilangeni", country: "Swaziland", flag: 'SZ'},
    { code: "THB", name: "Thai Baht", country: "Thailand", flag: 'TH'},
    { code: "TRY", name: "Turkish Lira", country: "Turkey", flag: 'TR'},
    { code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", flag: 'TW'},
    { code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", flag: 'UA'},
    { code: "USD", name: "United States Dollar", country: "United States of America", flag: 'US'},
    { code: "VND", name: "Vietnamese Dong", country: "Vietnam", flag: 'VN'},
    { code: "XOF", name: "West African CFA franc", country: "West African Economic and Monetary Union (UEMOA)", flag: 'a'},
    { code: "ZAR", name: "South African Rand", country: "South Africa", flag: 'ZA'},
    ]
